[features]
seeds = false
[programs.devnet]
nft_dex = "FPXufVFzjVreF5ResTtw44hPpir4zRRkUiMK6xJeuMfL"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/wb-ts/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
