[features]
seeds = false
[programs.devnet]
nft_dex = "BQNWkSGD2TtpGVLq4TLcpWgEb2B2uSimixxVYbXP7NR9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/kyle/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
